import type { MetadataRoute } from "next";
import { site } from "@/lib/site";

/**
 * Web App Manifest — generated at /manifest.webmanifest.
 *
 * Icons live in /public/favicon_io (generated by favicon.io). Theme colours
 * track the brand navy from globals.css.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${site.shortName} — ${site.candidate} for ${site.constituency}`,
    short_name: `${site.shortName} for Ibadan`,
    description: site.slogan,
    start_url: "/",
    display: "standalone",
    background_color: "#071a26",
    theme_color: "#071a26",
    lang: "en-NG",
    categories: ["politics", "government", "news"],
    icons: [
      {
        src: "/favicon_io/android-chrome-192x192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/favicon_io/android-chrome-512x512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/favicon_io/apple-touch-icon.png",
        sizes: "180x180",
        type: "image/png",
      },
    ],
  };
}
